<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGRX9cnW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGRX9cnW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGRX9cnW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGRX9cnW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGRX9cnW\App_KernelDevDebugContainer([
    'container.build_hash' => 'GRX9cnW',
    'container.build_id' => '0be62cff',
    'container.build_time' => 1611161844,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGRX9cnW');
